//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adresse
    {
        public int Id { get; set; }
        public string Dit_fulde_navn { get; set; }
        public string Adresse1 { get; set; }
        public string City { get; set; }
        public Nullable<int> Postnummer { get; set; }
        public string Email { get; set; }
        public Nullable<int> TelefonNum { get; set; }
        public Nullable<System.DateTime> Foedselsdagsdato { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<System.DateTime> ModificationDateTime { get; set; }
    }
}
