//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bobestyrer
    {
        public int Id { get; set; }
        public int TestamentId { get; set; }
        public string Navn { get; set; }
        public string Adresse { get; set; }
        public Nullable<int> Postnummer { get; set; }
        public string Bynavn { get; set; }
        public string Kommentarer_til_bobestyrer { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<System.DateTime> ModificationDateTime { get; set; }
    
        public virtual Testamenta_form_API Testamenta_form_API { get; set; }
        public virtual Testamenta_form Testamenta_form { get; set; }
    }
}
