//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrganisationArvinger
    {
        public int Id { get; set; }
        public string Session_id { get; set; }
        public int OrganisationId { get; set; }
        public string ArvEllerLegatar { get; set; }
        public Nullable<bool> Fortrinsret { get; set; }
        public string Genstande { get; set; }
        public Nullable<bool> BaandlaeggeArv { get; set; }
        public string Hvornaar_skal_baandlaeggelsen_ophoere { get; set; }
        public Nullable<decimal> FordelingiPct { get; set; }
        public string Ejendele { get; set; }
        public Nullable<bool> ErActive { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<System.DateTime> ModificationDateTime { get; set; }
    
        public virtual SESSIONS_API SESSIONS_API { get; set; }
    }
}
