//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SESSIONS_API
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SESSIONS_API()
        {
            this.Testamenta_form_API = new HashSet<Testamenta_form_API>();
            this.TestamentaOpretter = new HashSet<TestamentaOpretter>();
            this.OrganisationArvinger = new HashSet<OrganisationArvinger>();
            this.Arvinger = new HashSet<Arvinger>();
            this.Testamenta_form = new HashSet<Testamenta_form>();
        }
    
        public string session_id { get; set; }
        public string country { get; set; }
        public string city { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> createdDateTime { get; set; }
        public Nullable<System.DateTime> modificationDateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Testamenta_form_API> Testamenta_form_API { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestamentaOpretter> TestamentaOpretter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrganisationArvinger> OrganisationArvinger { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Arvinger> Arvinger { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Testamenta_form> Testamenta_form { get; set; }
    }
}
