//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestamentaOpretter
    {
        public int Id { get; set; }
        public string Navn { get; set; }
        public Nullable<bool> har_du_tidligere_opretettet_testamente_selv { get; set; }
        public string Saerejeform { get; set; }
        public bool MaaSaerejetAendres { get; set; }
        public string Aendringsbetingelser { get; set; }
        public bool Fortrinsret { get; set; }
        public string Genstande { get; set; }
        public string Type { get; set; }
        public string SessionId { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<System.DateTime> ModificationDateTime { get; set; }
        public bool Har_du_tidligere_oprettet_testamenta { get; set; }
        public bool Sidder_du_i_uskiftet_bo { get; set; }
        public string Dit_Afdoede_aegtefaelles_navn { get; set; }
        public bool har_du_saereje { get; set; }
    
        public virtual SESSIONS_API SESSIONS_API { get; set; }
    }
}
