//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vaerge
    {
        public int Id { get; set; }
        public int TestamentOpretteId { get; set; }
        public string Navn { get; set; }
        public Nullable<decimal> Raadighedsbelob_til_vaergen { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<System.DateTime> ModificationDateTime { get; set; }
    
        public virtual TestamentaOpretter TestamentaOpretter { get; set; }
        public virtual TestamentOpretter TestamentOpretter { get; set; }
    }
}
