//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class VedgoerendeOrganisation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VedgoerendeOrganisation()
        {
            this.Arvinger = new HashSet<Arvinger>();
        }
    
        public int Id { get; set; }
        public string Navn { get; set; }
        public int CVR { get; set; }
        public string Address { get; set; }
        public int PostNummer { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public bool ErAktiv { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<System.DateTime> ModificationDateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Arvinger> Arvinger { get; set; }
    }
}
